using SYSTEMATIC.INFRASTRUCTURE.Exceptions;

namespace SYSTEMATIC.INFRASTRUCTURE.Middleware
{
    public class ErrorHandlingMiddleware : IMiddleware
    {
        public async Task InvokeAsync(HttpContext context, RequestDelegate next)
        {
            try
            {
                await next.Invoke(context);
            }
            catch (NotFoundException notFoundException)
            {
                context.Response.StatusCode = 404;
                await context.Response.WriteAsync(notFoundException.Message);
            }
            catch (ExpiredException expiredException)
            {
                context.Response.StatusCode = 400;
                await context.Response.WriteAsync(expiredException.Message);
            }
            catch (Exception)
            {
                context.Response.StatusCode = 500;
                await context.Response.WriteAsync("Something went wrong");
            }
        }
    }
}
